services:
  # A Flask web service
  - type: web
    name: global-timesync-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: main.py
      - key: FLASK_DEBUG
        value: 0
      - key: TIMEZONE_INFO_CACHE_TTL
        value: 300
      - key: DEFAULT_CACHE_TTL
        value: 3600
      - key: PORT
        sync: false # PORT is provided by Render
      - key: JWT_SECRET
        generateValue: true # Auto-generate a secret key
      - key: DATABASE_URL
        fromDatabase:
          name: timesync-db
          property: connectionString

# Optional PostgreSQL database
databases:
  - name: timesync-db
    plan: free