services:
  # A Flask web service
  - type: web
    name: global-timesync-api
    env: python
    plan: free
    repo: https://github.com/Mayanshh/Global-TimesSync-Api.git
    buildCommand: |
      if ! pip install poetry && poetry install; then
        # Fallback to installing packages directly
        pip install bcrypt==4.0.1 email-validator==2.0.0 fastapi==0.95.1 flask==2.3.2 flask-sqlalchemy==3.0.3 \
                    gunicorn==23.0.0 passlib==1.7.4 psycopg2-binary==2.9.6 pydantic==1.10.7 pyjwt==2.7.0 \
                    python-dateutil==2.8.2 python-dotenv==1.0.0 python-jose==3.3.0 python-multipart==0.0.6 \
                    pytz==2023.3 uvicorn==0.22.0
      fi
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: main.py
      - key: FLASK_DEBUG
        value: 0
      - key: TIMEZONE_INFO_CACHE_TTL
        value: 300
      - key: DEFAULT_CACHE_TTL
        value: 3600
      - key: PORT
        sync: false # PORT is provided by Render
      - key: JWT_SECRET
        generateValue: true # Auto-generate a secret key
      - key: DATABASE_URL
        fromDatabase:
          name: timesync-db
          property: connectionString

# Optional PostgreSQL database
databases:
  - name: timesync-db
    plan: free